#include "token.hpp"
#include "common.hpp"

const char* Token::TagToCstr(Tag tag)
{
    switch (tag)
    {
    case Tag::kKeywordCreate:
        return "CREATE";
    case Tag::kKeywordTable:
        return "TABLE";
    case Tag::kKeywordDefault:
        return "DEFAULT";
    case Tag::kKeywordConstraint:
        return "CONSTRAINT";
    case Tag::kKeywordNot:
        return "NOT";
    case Tag::kKeywordUnique:
        return "UNIQUE";
    case Tag::kKeywordPrimary:
        return "PRIMARY";
    case Tag::kKeywordKey:
        return "KEY";
    case Tag::kKeywordCheck:
        return "CHECK";
    case Tag::kKeywordDrop:
        return "DROP";
    case Tag::kKeywordInsert:
        return "INSERT";
    case Tag::kKeywordInto:
        return "INTO";
    case Tag::kKeywordValues:
        return "VALUES";
    case Tag::kKeywordSelect:
        return "SELECT";
    case Tag::kKeywordDistinct:
        return "DISTINCT";
    case Tag::kKeywordAll:
        return "ALL";
    case Tag::kKeywordFrom:
        return "FROM";
    case Tag::kKeywordAs:
        return "AS";
    case Tag::kKeywordJoin:
        return "JOIN";
    case Tag::kKeywordCross:
        return "CROSS";
    case Tag::kKeywordInner:
        return "INNER";
    case Tag::kKeywordOuter:
        return "OUTER";
    case Tag::kKeywordLeft:
        return "LEFT";
    case Tag::kKeywordRight:
        return "RIGHT";
    case Tag::kKeywordFull:
        return "FULL";
    case Tag::kKeywordOn:
        return "ON";
    case Tag::kKeywordWhere:
        return "WHERE";
    case Tag::kKeywordGroup:
        return "GROUP";
    case Tag::kKeywordBy:
        return "BY";
    case Tag::kKeywordHaving:
        return "HAVING";
    case Tag::kKeywordUnion:
        return "UNION";
    case Tag::kKeywordExcept:
        return "EXCEPT";
    case Tag::kKeywordIntersect:
        return "INTERSECT";
    case Tag::kKeywordOrder:
        return "ORDER";
    case Tag::kKeywordAsc:
        return "ASC";
    case Tag::kKeywordDesc:
        return "DESC";
    case Tag::kKeywordInteger:
        return "INTEGER";
    case Tag::kKeywordReal:
        return "REAL";
    case Tag::kKeywordVarchar:
        return "VARCHAR";
    case Tag::kKeywordBetween:
        return "BETWEEN";
    case Tag::kKeywordIn:
        return "IN";
    case Tag::kKeywordIs:
        return "IS";
    case Tag::kKeywordExists:
        return "EXISTS";
    case Tag::kKeywordCast:
        return "CAST";
    case Tag::kKeywordNull:
        return "NULL";
    case Tag::kKeywordLimit:
        return "LIMIT";
    case Tag::kKeywordDelete:
        return "DELETE";
    case Tag::kKeywordUpdate:
        return "UPDATE";
    case Tag::kKeywordSet:
        return "SET";
    case Tag::kLParen:
        return "(";
    case Tag::kRParen:
        return ")";
    case Tag::kPeriod:
        return ".";
    case Tag::kComma:
        return ",";
    case Tag::kSemicolon:
        return ";";
    case Tag::kAsterisk:
        return "*";
    case Tag::kOp2:
        return "an operator";
    case Tag::kFunction:
        return "an aggregation function";
    case Tag::kIdentifier:
        return "an identifier";
    case Tag::kConstant:
        return "a constant";
    case Tag::kEnd:
        return "end of source";
    }
    UNREACHABLE();
}