name: CI Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake clang clang-tidy
      - name: Run format check
        run: |
          cmake -S . -B build/format
          cmake --build build/format --target formatCheck

  build_and_test:
    needs: format
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # windows-latest
        build_config: [debug, release, static]
        include:
        - build_config: debug
          type: Debug
          tidy: OFF
          werror: OFF
        - build_config: release
          type: Release
          tidy: OFF
          werror: OFF
        - build_config: static
          type: Release
          tidy: ON
          werror: ON

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake clang clang-tidy

      - name: Configure CMake
        run: >
          cmake -S . -B build 
          -DCMAKE_BUILD_TYPE=${{ matrix.type }}
          -DENABLE_CLANG_TIDY=${{ matrix.tidy }}
          -DENABLE_WERROR=${{ matrix.werror }}

      - name: Build
        run: cmake --build build --config ${{ matrix.type }}

      - name: Unit Tests
        working-directory: build
        run: ctest -C ${{ matrix.type }} -L "unit" --output-on-failure

      - name: Stress Tests
        working-directory: build
        run: ctest -C ${{ matrix.type }} -L "stress" --output-on-failure